export interface CuratedBook {
  id: string;
  source: "vellum";
  title: string;
  author: string;
  category: string;
  gradeLevel: string | null;
  subject: string;
  language: string;
  description: string;
  coverUrl: string;
  ia: string;
  isNational?: boolean;
  isFeatured?: boolean;
  isReadable: boolean;
  publishYear: number;
}

export const CURATED_100_BOOKS: CuratedBook[] = [
  // --- SCIENCE & ASTRONOMY (1-20) ---
  {
    id: "bk-001",
    source: "vellum",
    title: "Relativity: The Special and General Theory",
    author: "Albert Einstein",
    category: "Science",
    gradeLevel: "11",
    subject: "Physics",
    language: "en",
    description: "A clear explanation of the foundations of modern physics and spacetime curvature by the discoverer himself.",
    coverUrl: "https://covers.openlibrary.org/b/id/8231856-M.jpg",
    ia: "relativityspecia00eins",
    isFeatured: true,
    isReadable: true,
    publishYear: 1920,
  },
  {
    id: "bk-002",
    source: "vellum",
    title: "The Origin of Species",
    author: "Charles Darwin",
    category: "Science",
    gradeLevel: "10",
    subject: "Biology",
    language: "en",
    description: "The seminal work establishing evolutionary biology, adaptation, and natural selection.",
    coverUrl: "https://covers.openlibrary.org/b/id/8301777-M.jpg",
    ia: "originofspecies00darwuoft",
    isFeatured: true,
    isReadable: true,
    publishYear: 1859,
  },
  {
    id: "bk-003",
    source: "vellum",
    title: "Opticks: Or, A Treatise of Light",
    author: "Isaac Newton",
    category: "Science",
    gradeLevel: "11",
    subject: "Physics",
    language: "en",
    description: "Foundational investigations into light refraction, color prisms, and optical reflection.",
    coverUrl: "https://covers.openlibrary.org/b/id/6524316-M.jpg",
    ia: "opticksortreatis00newt",
    isFeatured: false,
    isReadable: true,
    publishYear: 1704,
  },
  {
    id: "bk-004",
    source: "vellum",
    title: "Dialogues Concerning Two New Sciences",
    author: "Galileo Galilei",
    category: "Science",
    gradeLevel: "12",
    subject: "Physics",
    language: "en",
    description: "Galileo's masterwork formulating the laws of kinematics and material strength.",
    coverUrl: "https://covers.openlibrary.org/b/id/7891234-M.jpg",
    ia: "dialoguesconcern00galiuoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1638,
  },
  {
    id: "bk-005",
    source: "vellum",
    title: "The Sceptical Chymist",
    author: "Robert Boyle",
    category: "Science",
    gradeLevel: "10",
    subject: "Chemistry",
    language: "en",
    description: "The cornerstone of modern chemistry replacing alchemy with experimental rigor and atomic theory.",
    coverUrl: "https://covers.openlibrary.org/b/id/6712391-M.jpg",
    ia: "scepticalchymist00boyl",
    isFeatured: false,
    isReadable: true,
    publishYear: 1661,
  },
  {
    id: "bk-006",
    source: "vellum",
    title: "Experiments and Observations on Electricity",
    author: "Benjamin Franklin",
    category: "Science",
    gradeLevel: "9",
    subject: "Physics",
    language: "en",
    description: "Classic electrical experiments establishing positive and negative charges, lightning rods, and circuits.",
    coverUrl: "https://covers.openlibrary.org/b/id/7219941-M.jpg",
    ia: "experimentsobser00fran",
    isFeatured: false,
    isReadable: true,
    publishYear: 1751,
  },
  {
    id: "bk-007",
    source: "vellum",
    title: "A Treatise on Electricity and Magnetism",
    author: "James Clerk Maxwell",
    category: "Science",
    gradeLevel: "college",
    subject: "Physics",
    language: "en",
    description: "Unified electromagnetic theory that laid the foundation for modern radio, electronics, and quantum optics.",
    coverUrl: "https://covers.openlibrary.org/b/id/6910245-M.jpg",
    ia: "treatiseonelectr01maxwrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1873,
  },
  {
    id: "bk-008",
    source: "vellum",
    title: "Principles of Geology",
    author: "Charles Lyell",
    category: "Science",
    gradeLevel: "9",
    subject: "Earth Science",
    language: "en",
    description: "The founding text of uniformitarian geology, plate dynamics, and sedimentary strata.",
    coverUrl: "https://covers.openlibrary.org/b/id/7421890-M.jpg",
    ia: "principlesofgeol01lyel",
    isFeatured: false,
    isReadable: true,
    publishYear: 1830,
  },
  {
    id: "bk-009",
    source: "vellum",
    title: "Micrographia: Physiological Descriptions of Minute Bodies",
    author: "Robert Hooke",
    category: "Science",
    gradeLevel: "9",
    subject: "Biology",
    language: "en",
    description: "First historical recording of biological cells using early compound microscopy.",
    coverUrl: "https://covers.openlibrary.org/b/id/8119023-M.jpg",
    ia: "micrographiaorph00hook",
    isFeatured: false,
    isReadable: true,
    publishYear: 1665,
  },
  {
    id: "bk-010",
    source: "vellum",
    title: "The Chemical History of a Candle",
    author: "Michael Faraday",
    category: "Science",
    gradeLevel: "8",
    subject: "Chemistry",
    language: "en",
    description: "Six engaging lecture demonstrations exploring combustion, oxygen, carbon, and thermal physics.",
    coverUrl: "https://covers.openlibrary.org/b/id/7319082-M.jpg",
    ia: "chemicalhistoryo00fara",
    isFeatured: true,
    isReadable: true,
    publishYear: 1861,
  },
  {
    id: "bk-011",
    source: "vellum",
    title: "Radioactive Substances",
    author: "Marie Curie",
    category: "Science",
    gradeLevel: "12",
    subject: "Chemistry",
    language: "en",
    description: "Nobel Prize thesis discovering polonium and radium, detailing alpha, beta, and gamma radiation.",
    coverUrl: "https://covers.openlibrary.org/b/id/8401923-M.jpg",
    ia: "radioactivesubst00curirich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1904,
  },
  {
    id: "bk-012",
    source: "vellum",
    title: "Elementary Chemistry for High Schools",
    author: "Alexander Smith",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Chemistry",
    language: "en",
    description: "Comprehensive secondary school textbook on inorganic reactions, molar masses, and chemical bonding.",
    coverUrl: "https://covers.openlibrary.org/b/id/6810294-M.jpg",
    ia: "elementarychemis00smitrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1914,
  },
  {
    id: "bk-013",
    source: "vellum",
    title: "An Introduction to Astronomy",
    author: "Forest Ray Moulton",
    category: "Science",
    gradeLevel: "10",
    subject: "Astronomy",
    language: "en",
    description: "A complete textbook covering planetary orbits, stellar constellations, lunar eclipses, and telescopes.",
    coverUrl: "https://covers.openlibrary.org/b/id/7621094-M.jpg",
    ia: "introductiontoas00moulrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1906,
  },
  {
    id: "bk-014",
    source: "vellum",
    title: "General Physiology: An Outline of the Science of Life",
    author: "Max Verworn",
    category: "Science",
    gradeLevel: "12",
    subject: "Biology",
    language: "en",
    description: "Detailed cellular biology examining cell metabolism, muscular contractions, and neural impulses.",
    coverUrl: "https://covers.openlibrary.org/b/id/7901243-M.jpg",
    ia: "generalphysiolog00verwrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1899,
  },
  {
    id: "bk-015",
    source: "vellum",
    title: "The Story of the Living Machine",
    author: "H. W. Conn",
    category: "Science",
    gradeLevel: "8",
    subject: "Biology",
    language: "en",
    description: "An accessible review of cellular machinery, enzymes, nutrition, and metabolic systems.",
    coverUrl: "https://covers.openlibrary.org/b/id/7123910-M.jpg",
    ia: "storyoflivingmac00connrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1899,
  },
  {
    id: "bk-016",
    source: "vellum",
    title: "A First Course in Physics",
    author: "Robert A. Millikan & Henry G. Gale",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Physics",
    language: "en",
    description: "Classic high school physics textbook teaching vectors, mechanics, sound, and thermodynamics.",
    coverUrl: "https://covers.openlibrary.org/b/id/6920194-M.jpg",
    ia: "firstcourseinphy00millrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1906,
  },
  {
    id: "bk-017",
    source: "vellum",
    title: "The Structure of the Atom",
    author: "E. N. da C. Andrade",
    category: "Science",
    gradeLevel: "12",
    subject: "Physics",
    language: "en",
    description: "Rutherford and Bohr atomic models, electron shells, isotopes, and nuclear structure.",
    coverUrl: "https://covers.openlibrary.org/b/id/8319204-M.jpg",
    ia: "structureofatome00andrrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1923,
  },
  {
    id: "bk-018",
    source: "vellum",
    title: "Botany for Beginners",
    author: "Ernest Evans",
    category: "Science",
    gradeLevel: "7",
    subject: "Biology",
    language: "en",
    description: "Introductory plant biology: germination, leaf structures, photosynthesis, and pollination.",
    coverUrl: "https://covers.openlibrary.org/b/id/7019284-M.jpg",
    ia: "botanyforbeginne00evanrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1901,
  },
  {
    id: "bk-019",
    source: "vellum",
    title: "Weather and Weather Instruments",
    author: "P. R. Jameson",
    category: "Science",
    gradeLevel: "8",
    subject: "Earth Science",
    language: "en",
    description: "Barometers, thermometers, hygrometers, cloud classification, and meteorological forecasting.",
    coverUrl: "https://covers.openlibrary.org/b/id/7219084-M.jpg",
    ia: "weatherweatherin00jamerich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1908,
  },
  {
    id: "bk-020",
    source: "vellum",
    title: "The Human Body: Its Structure and Activities",
    author: "H. Newell Martin",
    category: "Textbook",
    gradeLevel: "10",
    subject: "Biology",
    language: "en",
    description: "Anatomy and human physiology: circulatory system, lungs, brain, skeletal joints, and digestion.",
    coverUrl: "https://covers.openlibrary.org/b/id/7721904-M.jpg",
    ia: "humanbodyitsstru00martrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1898,
  },

  // --- MATHEMATICS & LOGIC (21-40) ---
  {
    id: "bk-021",
    source: "vellum",
    title: "The Thirteen Books of Euclid's Elements",
    author: "Euclid (tr. Thomas L. Heath)",
    category: "Mathematics",
    gradeLevel: "9",
    subject: "Geometry",
    language: "en",
    description: "The definitive compilation of plane and solid Euclidean geometry, prime numbers, and proportion.",
    coverUrl: "https://covers.openlibrary.org/b/id/8120394-M.jpg",
    ia: "thirteenbooksofe01eucl",
    isFeatured: true,
    isReadable: true,
    publishYear: 1908,
  },
  {
    id: "bk-022",
    source: "vellum",
    title: "The Foundations of Geometry",
    author: "David Hilbert",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Geometry",
    language: "en",
    description: "Modern formal axiomatization of geometry establishing independence and consistency.",
    coverUrl: "https://covers.openlibrary.org/b/id/7410294-M.jpg",
    ia: "foundationsofgeo00hilbrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1902,
  },
  {
    id: "bk-023",
    source: "vellum",
    title: "Calculus Made Easy",
    author: "Silvanus P. Thompson",
    category: "Mathematics",
    gradeLevel: "11",
    subject: "Calculus",
    language: "en",
    description: "The most famous, intuitive introduction to differential and integral calculus ever written.",
    coverUrl: "https://covers.openlibrary.org/b/id/8321045-M.jpg",
    ia: "calculusmadeeasy00thomrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1914,
  },
  {
    id: "bk-024",
    source: "vellum",
    title: "A Course of Pure Mathematics",
    author: "G. H. Hardy",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Analysis",
    language: "en",
    description: "Rigorous mathematical analysis: real numbers, series limits, derivatives, and continuous functions.",
    coverUrl: "https://covers.openlibrary.org/b/id/7810294-M.jpg",
    ia: "courseofpuremath00hardrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1908,
  },
  {
    id: "bk-025",
    source: "vellum",
    title: "High School Algebra",
    author: "J. T. Crawford",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Algebra",
    language: "en",
    description: "Quadratic equations, polynomials, simultaneous systems, factoring, and binomial theorem.",
    coverUrl: "https://covers.openlibrary.org/b/id/7102945-M.jpg",
    ia: "highschoolalgebr00crawrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1916,
  },
  {
    id: "bk-026",
    source: "vellum",
    title: "Plane and Spherical Trigonometry",
    author: "George Wentworth & David Eugene Smith",
    category: "Textbook",
    gradeLevel: "10",
    subject: "Trigonometry",
    language: "en",
    description: "Trigonometric ratios, sine and cosine laws, logarithmic navigation, and triangular survey.",
    coverUrl: "https://covers.openlibrary.org/b/id/6920184-M.jpg",
    ia: "planesphericaltr00wentrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1915,
  },
  {
    id: "bk-027",
    source: "vellum",
    title: "An Introduction to the Theory of Statistics",
    author: "G. Udny Yule",
    category: "Mathematics",
    gradeLevel: "12",
    subject: "Statistics",
    language: "en",
    description: "Frequency distributions, standard deviation, correlation coefficients, and normal distribution curves.",
    coverUrl: "https://covers.openlibrary.org/b/id/8012945-M.jpg",
    ia: "introductiontoth00yulerich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1911,
  },
  {
    id: "bk-028",
    source: "vellum",
    title: "The Principles of Mathematics",
    author: "Bertrand Russell",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Logic",
    language: "en",
    description: "Russell's classic formulating logicism: the deduction of mathematics from symbolic formal logic.",
    coverUrl: "https://covers.openlibrary.org/b/id/7510294-M.jpg",
    ia: "principlesofmath00russuoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1903,
  },
  {
    id: "bk-029",
    source: "vellum",
    title: "First Steps in Number",
    author: "G. A. Wentworth & E. M. Reed",
    category: "Textbook",
    gradeLevel: "1",
    subject: "Arithmetic",
    language: "en",
    description: "Foundational arithmetic for primary education: counting, addition, subtraction, and visual sets.",
    coverUrl: "https://covers.openlibrary.org/b/id/6819204-M.jpg",
    ia: "firststepsinnum00wentrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1887,
  },
  {
    id: "bk-030",
    source: "vellum",
    title: "Intermediate Arithmetic",
    author: "Frank H. Hall",
    category: "Textbook",
    gradeLevel: "5",
    subject: "Arithmetic",
    language: "en",
    description: "Fractions, decimals, percentages, measurements, and word problems for elementary grades.",
    coverUrl: "https://covers.openlibrary.org/b/id/7301924-M.jpg",
    ia: "intermediateari00hallrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1899,
  },
  {
    id: "bk-031",
    source: "vellum",
    title: "Solid Geometry",
    author: "Clara A. Hart & Daniel D. Feldman",
    category: "Textbook",
    gradeLevel: "10",
    subject: "Geometry",
    language: "en",
    description: "Polyhedrons, cylinders, cones, spheres, surface area formulas, and 3D spatial proofs.",
    coverUrl: "https://covers.openlibrary.org/b/id/7601924-M.jpg",
    ia: "solidgeometry00hartrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1912,
  },
  {
    id: "bk-032",
    source: "vellum",
    title: "A Treatise on Differential Equations",
    author: "A. R. Forsyth",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Calculus",
    language: "en",
    description: "First-order differential equations, linear second-order equations, and partial differential methods.",
    coverUrl: "https://covers.openlibrary.org/b/id/8201945-M.jpg",
    ia: "treatiseondiffer00forsrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1888,
  },
  {
    id: "bk-033",
    source: "vellum",
    title: "Mathematical Recreations and Essays",
    author: "W. W. Rouse Ball",
    category: "Mathematics",
    gradeLevel: "8",
    subject: "Puzzles",
    language: "en",
    description: "Magic squares, mazes, knight's tours on chessboards, geometric paradoxes, and cryptography.",
    coverUrl: "https://covers.openlibrary.org/b/id/7901924-M.jpg",
    ia: "mathematicalrecr00balluoft",
    isFeatured: true,
    isReadable: true,
    publishYear: 1892,
  },
  {
    id: "bk-034",
    source: "vellum",
    title: "The Teaching of Elementary Mathematics",
    author: "David Eugene Smith",
    category: "Textbook",
    gradeLevel: "lifelong",
    subject: "Education",
    language: "en",
    description: "Pedagogy and history of arithmetic, algebra, and geometry instruction for teachers and educators.",
    coverUrl: "https://covers.openlibrary.org/b/id/7401924-M.jpg",
    ia: "teachingofelemen00smitrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1900,
  },
  {
    id: "bk-035",
    source: "vellum",
    title: "Vector Analysis: A Text-book for the Use of Students",
    author: "J. Willard Gibbs & Edwin Bidwell Wilson",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Linear Algebra",
    language: "en",
    description: "Dot products, cross products, gradient, divergence, curl, and vector calculus in 3-space.",
    coverUrl: "https://covers.openlibrary.org/b/id/8101924-M.jpg",
    ia: "vectoranalysiste00gibbarch",
    isFeatured: false,
    isReadable: true,
    publishYear: 1901,
  },
  {
    id: "bk-036",
    source: "vellum",
    title: "Plane Surveying: A Text-book and Pocket Manual",
    author: "John Clayton Tracy",
    category: "Mathematics",
    gradeLevel: "11",
    subject: "Surveying",
    language: "en",
    description: "Theodolite measurements, leveling, topographic maps, triangulation, and civil field calculations.",
    coverUrl: "https://covers.openlibrary.org/b/id/7201945-M.jpg",
    ia: "planesurveyingte00tracrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1907,
  },
  {
    id: "bk-037",
    source: "vellum",
    title: "Elements of the Theory of Integers",
    author: "Joseph Bowden",
    category: "Mathematics",
    gradeLevel: "12",
    subject: "Number Theory",
    language: "en",
    description: "Peano axioms, divisibility, modular arithmetic, prime factorizations, and mathematical induction.",
    coverUrl: "https://covers.openlibrary.org/b/id/7701924-M.jpg",
    ia: "elementsoftheory00bowdrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1903,
  },
  {
    id: "bk-038",
    source: "vellum",
    title: "A Treatise on Probability",
    author: "John Maynard Keynes",
    category: "Mathematics",
    gradeLevel: "college",
    subject: "Probability",
    language: "en",
    description: "Philosophical and mathematical foundations of logical probability, induction, and statistical inference.",
    coverUrl: "https://covers.openlibrary.org/b/id/8301924-M.jpg",
    ia: "treatiseonprobab00keynrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1921,
  },
  {
    id: "bk-039",
    source: "vellum",
    title: "First Year in Algebra",
    author: "Frederick H. Somerville",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Algebra",
    language: "en",
    description: "Introductory algebraic notation, positive and negative integers, linear equations, and graphs.",
    coverUrl: "https://covers.openlibrary.org/b/id/7001924-M.jpg",
    ia: "firstyearinalgeb00somerich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1905,
  },
  {
    id: "bk-040",
    source: "vellum",
    title: "The Philosophy of Arithmetic",
    author: "Edward Brooks",
    category: "Mathematics",
    gradeLevel: "lifelong",
    subject: "Philosophy",
    language: "en",
    description: "An inquiry into the nature and history of numbers, computation, fractions, and ratio systems.",
    coverUrl: "https://covers.openlibrary.org/b/id/7501924-M.jpg",
    ia: "philosophyofar00broorich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1880,
  },

  // --- WORLD HISTORY & CIVILIZATIONS (41-60) ---
  {
    id: "bk-041",
    source: "vellum",
    title: "The History of Herodotus",
    author: "Herodotus (tr. George Rawlinson)",
    category: "History",
    gradeLevel: "10",
    subject: "Ancient History",
    language: "en",
    description: "The father of history chronicles the Persian Wars, ancient Egypt, Babylon, and early Mediterranean cultures.",
    coverUrl: "https://covers.openlibrary.org/b/id/8201984-M.jpg",
    ia: "historyofherodot01hero",
    isFeatured: true,
    isReadable: true,
    publishYear: 1858,
  },
  {
    id: "bk-042",
    source: "vellum",
    title: "History of the Peloponnesian War",
    author: "Thucydides (tr. Benjamin Jowett)",
    category: "History",
    gradeLevel: "11",
    subject: "Ancient History",
    language: "en",
    description: "The definitive chronicle of the epic struggle between Athens and Sparta, analyzing power and democracy.",
    coverUrl: "https://covers.openlibrary.org/b/id/8101984-M.jpg",
    ia: "thucydides01thucrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1881,
  },
  {
    id: "bk-043",
    source: "vellum",
    title: "The Decline and Fall of the Roman Empire",
    author: "Edward Gibbon",
    category: "History",
    gradeLevel: "12",
    subject: "World History",
    language: "en",
    description: "Monuments of Western historiography detailing Rome's transition from empire to medieval Christendom.",
    coverUrl: "https://covers.openlibrary.org/b/id/8401984-M.jpg",
    ia: "historyofdecline01gibb",
    isFeatured: true,
    isReadable: true,
    publishYear: 1776,
  },
  {
    id: "bk-044",
    source: "vellum",
    title: "A History of Ethiopia",
    author: "E. A. Wallis Budge",
    category: "History",
    gradeLevel: "9",
    subject: "Ethiopian History",
    language: "en",
    description: "Comprehensive history of the Aksumite Kingdom, Solomonic dynasty, medieval chronicles, and cultural heritage.",
    coverUrl: "https://covers.openlibrary.org/b/id/8501984-M.jpg",
    ia: "historyofethiopi01budg",
    isNational: true,
    isFeatured: true,
    isReadable: true,
    publishYear: 1928,
  },
  {
    id: "bk-045",
    source: "vellum",
    title: "Travels in Nubia and Abyssinia",
    author: "James Bruce",
    category: "History",
    gradeLevel: "10",
    subject: "Geography",
    language: "en",
    description: "18th-century journey discovering the source of the Blue Nile at Lake Tana and exploring Gondar.",
    coverUrl: "https://covers.openlibrary.org/b/id/8601984-M.jpg",
    ia: "travelstodiscove03bruc",
    isNational: true,
    isFeatured: false,
    isReadable: true,
    publishYear: 1790,
  },
  {
    id: "bk-046",
    source: "vellum",
    title: "A Short History of the World",
    author: "H. G. Wells",
    category: "History",
    gradeLevel: "8",
    subject: "World History",
    language: "en",
    description: "From geological emergence and early human migrations through ancient empires and the modern industrial era.",
    coverUrl: "https://covers.openlibrary.org/b/id/8301984-M.jpg",
    ia: "shorthistoryofwo00well",
    isFeatured: true,
    isReadable: true,
    publishYear: 1922,
  },
  {
    id: "bk-047",
    source: "vellum",
    title: "The Story of Mankind",
    author: "Hendrik Willem van Loon",
    category: "History",
    gradeLevel: "7",
    subject: "World History",
    language: "en",
    description: "The Newbery Medal winning narrative history of human civilizations, art, writing, and inventions.",
    coverUrl: "https://covers.openlibrary.org/b/id/7901984-M.jpg",
    ia: "storyofmankind00vanl",
    isFeatured: false,
    isReadable: true,
    publishYear: 1921,
  },
  {
    id: "bk-048",
    source: "vellum",
    title: "The Ancient World: From the Earliest Times",
    author: "Francis S. Betten",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Ancient History",
    language: "en",
    description: "Secondary textbook covering Mesopotamia, Egypt, Phoenicia, Greece, and the Roman Republic.",
    coverUrl: "https://covers.openlibrary.org/b/id/7701984-M.jpg",
    ia: "ancientworldfrom00bett",
    isFeatured: false,
    isReadable: true,
    publishYear: 1916,
  },
  {
    id: "bk-049",
    source: "vellum",
    title: "Medieval and Modern Times",
    author: "James Harvey Robinson",
    category: "Textbook",
    gradeLevel: "10",
    subject: "European History",
    language: "en",
    description: "The collapse of the Western Roman empire, the Renaissance, Reformation, and Enlightenment.",
    coverUrl: "https://covers.openlibrary.org/b/id/7501984-M.jpg",
    ia: "medievalmodernti00robi",
    isFeatured: false,
    isReadable: true,
    publishYear: 1919,
  },
  {
    id: "bk-050",
    source: "vellum",
    title: "The Discovery of Guiana",
    author: "Sir Walter Raleigh",
    category: "History",
    gradeLevel: "9",
    subject: "Exploration",
    language: "en",
    description: "Account of voyages along the Orinoco river, mapping South American indigenous trade routes.",
    coverUrl: "https://covers.openlibrary.org/b/id/7201984-M.jpg",
    ia: "discoveryoflarge00rale",
    isFeatured: false,
    isReadable: true,
    publishYear: 1596,
  },
  {
    id: "bk-051",
    source: "vellum",
    title: "The French Revolution: A History",
    author: "Thomas Carlyle",
    category: "History",
    gradeLevel: "11",
    subject: "Modern History",
    language: "en",
    description: "Epic historical narrative of the fall of the Bastille, the Reign of Terror, and the rise of Napoleon.",
    coverUrl: "https://covers.openlibrary.org/b/id/8001984-M.jpg",
    ia: "frenchrevolution01carl",
    isFeatured: false,
    isReadable: true,
    publishYear: 1837,
  },
  {
    id: "bk-052",
    source: "vellum",
    title: "Source Book of Medieval History",
    author: "Frederic Austin Ogg",
    category: "History",
    gradeLevel: "11",
    subject: "Medieval History",
    language: "en",
    description: "Original primary documents: Magna Carta, papal bulls, feudal oaths, and monastic rules.",
    coverUrl: "https://covers.openlibrary.org/b/id/7801984-M.jpg",
    ia: "sourcebookofmedi00oggrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1907,
  },
  {
    id: "bk-053",
    source: "vellum",
    title: "The Life of Nelson",
    author: "Robert Southey",
    category: "History",
    gradeLevel: "8",
    subject: "Biography",
    language: "en",
    description: "Classic naval biography of Admiral Horatio Nelson from the Nile to the Battle of Trafalgar.",
    coverUrl: "https://covers.openlibrary.org/b/id/7401984-M.jpg",
    ia: "lifeofnelson00soutrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1813,
  },
  {
    id: "bk-054",
    source: "vellum",
    title: "A History of the United States",
    author: "Charles A. Beard & Mary R. Beard",
    category: "Textbook",
    gradeLevel: "11",
    subject: "American History",
    language: "en",
    description: "Colonial settlements, the American Revolution, Constitutional Convention, and Civil War.",
    coverUrl: "https://covers.openlibrary.org/b/id/7601984-M.jpg",
    ia: "historyofuniteds00bearrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1921,
  },
  {
    id: "bk-055",
    source: "vellum",
    title: "Ancient Times: A History of the Early World",
    author: "James Henry Breasted",
    category: "Textbook",
    gradeLevel: "9",
    subject: "Archaeology",
    language: "en",
    description: "Pioneering archaeological history detailing the Fertile Crescent, hieroglyphs, and cuneiform.",
    coverUrl: "https://covers.openlibrary.org/b/id/8311984-M.jpg",
    ia: "ancienttimeshist00brearich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1916,
  },
  {
    id: "bk-056",
    source: "vellum",
    title: "The Industrial Revolution in the Eighteenth Century",
    author: "Paul Mantoux",
    category: "History",
    gradeLevel: "12",
    subject: "Economic History",
    language: "en",
    description: "The transition from cottage agriculture to steam machinery, coal mining, and factory organization.",
    coverUrl: "https://covers.openlibrary.org/b/id/8111984-M.jpg",
    ia: "industrialrevolu00mantrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1906,
  },
  {
    id: "bk-057",
    source: "vellum",
    title: "Famous Men of the Middle Ages",
    author: "John H. Haaren & A. B. Poland",
    category: "Textbook",
    gradeLevel: "6",
    subject: "Biography",
    language: "en",
    description: "Biographies of Charlemagne, William the Conqueror, Joan of Arc, Marco Polo, and Gutenberg.",
    coverUrl: "https://covers.openlibrary.org/b/id/7111984-M.jpg",
    ia: "famousmenofmiddl00haaruoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1904,
  },
  {
    id: "bk-058",
    source: "vellum",
    title: "Famous Men of Greece",
    author: "John H. Haaren & A. B. Poland",
    category: "Textbook",
    gradeLevel: "6",
    subject: "Biography",
    language: "en",
    description: "Achilles, Leonidas, Pericles, Socrates, and Alexander the Great presented for middle grades.",
    coverUrl: "https://covers.openlibrary.org/b/id/7011984-M.jpg",
    ia: "famousmenofgreec00haaruoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1904,
  },
  {
    id: "bk-059",
    source: "vellum",
    title: "Famous Men of Rome",
    author: "John H. Haaren & A. B. Poland",
    category: "Textbook",
    gradeLevel: "6",
    subject: "Biography",
    language: "en",
    description: "Romulus, Horatius, Scipio Africanus, Julius Caesar, and Marcus Aurelius.",
    coverUrl: "https://covers.openlibrary.org/b/id/6911984-M.jpg",
    ia: "famousmenofrome00haaruoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1904,
  },
  {
    id: "bk-060",
    source: "vellum",
    title: "Outlines of European History",
    author: "James Harvey Robinson & Charles A. Beard",
    category: "Textbook",
    gradeLevel: "10",
    subject: "European History",
    language: "en",
    description: "Two-volume standard secondary course from oriental civilizations through 19th-century nation-states.",
    coverUrl: "https://covers.openlibrary.org/b/id/7311984-M.jpg",
    ia: "outlinesofeurope01robi",
    isFeatured: false,
    isReadable: true,
    publishYear: 1914,
  },

  // --- LITERATURE & WORLD CLASSICS (61-80) ---
  {
    id: "bk-061",
    source: "vellum",
    title: "The Iliad of Homer",
    author: "Homer (tr. Alexander Pope)",
    category: "Literature",
    gradeLevel: "9",
    subject: "Epic Poetry",
    language: "en",
    description: "The siege of Troy, the wrath of Achilles, Hector's valor, and divine intervention in verse.",
    coverUrl: "https://covers.openlibrary.org/b/id/8221984-M.jpg",
    ia: "iliadofhomer01homeuoft",
    isFeatured: true,
    isReadable: true,
    publishYear: 1720,
  },
  {
    id: "bk-062",
    source: "vellum",
    title: "The Odyssey of Homer",
    author: "Homer (tr. Alexander Pope)",
    category: "Literature",
    gradeLevel: "9",
    subject: "Epic Poetry",
    language: "en",
    description: "Odysseus's ten-year voyage home to Ithaca past the Cyclops, sirens, and Scylla.",
    coverUrl: "https://covers.openlibrary.org/b/id/8121984-M.jpg",
    ia: "odysseyofhomer00home",
    isFeatured: false,
    isReadable: true,
    publishYear: 1726,
  },
  {
    id: "bk-063",
    source: "vellum",
    title: "Frankenstein: Or, The Modern Prometheus",
    author: "Mary Shelley",
    category: "Literature",
    gradeLevel: "10",
    subject: "Gothic Fiction",
    language: "en",
    description: "The founding masterwork of science fiction examining ambition, creation, and isolation.",
    coverUrl: "https://covers.openlibrary.org/b/id/8321984-M.jpg",
    ia: "frankensteinor00shel",
    isFeatured: true,
    isReadable: true,
    publishYear: 1818,
  },
  {
    id: "bk-064",
    source: "vellum",
    title: "The Time Machine",
    author: "H. G. Wells",
    category: "Literature",
    gradeLevel: "8",
    subject: "Science Fiction",
    language: "en",
    description: "A Victorian inventor journeys into the year 802,701 AD to encounter the Eloi and Morlocks.",
    coverUrl: "https://covers.openlibrary.org/b/id/8021984-M.jpg",
    ia: "timemachineanin00wellgoog",
    isFeatured: false,
    isReadable: true,
    publishYear: 1895,
  },
  {
    id: "bk-065",
    source: "vellum",
    title: "The War of the Worlds",
    author: "H. G. Wells",
    category: "Literature",
    gradeLevel: "8",
    subject: "Science Fiction",
    language: "en",
    description: "Martian fighting-machines with heat-rays and black smoke descend upon southern England.",
    coverUrl: "https://covers.openlibrary.org/b/id/7921984-M.jpg",
    ia: "warofworlds00wellrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1898,
  },
  {
    id: "bk-066",
    source: "vellum",
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    category: "Literature",
    gradeLevel: "7",
    subject: "Adventure",
    language: "en",
    description: "Captain Nemo and the submarine Nautilus explore ocean depths, coral reefs, and lost Atlantis.",
    coverUrl: "https://covers.openlibrary.org/b/id/8421984-M.jpg",
    ia: "twentythousandle00verniala",
    isFeatured: true,
    isReadable: true,
    publishYear: 1870,
  },
  {
    id: "bk-067",
    source: "vellum",
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    category: "Literature",
    gradeLevel: "7",
    subject: "Adventure",
    language: "en",
    description: "Phileas Fogg and Passepartout race steamships and trains across the globe on a wager.",
    coverUrl: "https://covers.openlibrary.org/b/id/7821984-M.jpg",
    ia: "aroundworldineig00vernrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1873,
  },
  {
    id: "bk-068",
    source: "vellum",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    category: "Literature",
    gradeLevel: "10",
    subject: "Historical Fiction",
    language: "en",
    description: "London and Paris during the French Revolution, featuring Sydney Carton's supreme sacrifice.",
    coverUrl: "https://covers.openlibrary.org/b/id/8521984-M.jpg",
    ia: "taleoftwocities00dickuoft",
    isFeatured: true,
    isReadable: true,
    publishYear: 1859,
  },
  {
    id: "bk-069",
    source: "vellum",
    title: "Great Expectations",
    author: "Charles Dickens",
    category: "Literature",
    gradeLevel: "10",
    subject: "Fiction",
    language: "en",
    description: "Pip's growth from village blacksmith apprentice to London gentleman under mysterious patronage.",
    coverUrl: "https://covers.openlibrary.org/b/id/8621984-M.jpg",
    ia: "greatexpectation00dickrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1861,
  },
  {
    id: "bk-070",
    source: "vellum",
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    category: "Literature",
    gradeLevel: "8",
    subject: "Mystery",
    language: "en",
    description: "Twelve detective cases solved by deductive reasoning, forensic observation, and logic at 221B Baker Street.",
    coverUrl: "https://covers.openlibrary.org/b/id/8721984-M.jpg",
    ia: "adventuresofsher00doylrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1892,
  },
  {
    id: "bk-071",
    source: "vellum",
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    category: "Literature",
    gradeLevel: "8",
    subject: "Mystery",
    language: "en",
    description: "Holmes and Watson investigate the demonic spectral hound stalking Dartmoor moorland.",
    coverUrl: "https://covers.openlibrary.org/b/id/8821984-M.jpg",
    ia: "houndofbaskervil00doylrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1902,
  },
  {
    id: "bk-072",
    source: "vellum",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Literature",
    gradeLevel: "10",
    subject: "Classics",
    language: "en",
    description: "Witty social critique of Regency England centering on Elizabeth Bennet and Mr. Darcy.",
    coverUrl: "https://covers.openlibrary.org/b/id/8921984-M.jpg",
    ia: "prideandprejudic00austrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1813,
  },
  {
    id: "bk-073",
    source: "vellum",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    category: "Literature",
    gradeLevel: "11",
    subject: "Classics",
    language: "en",
    description: "An orphaned governess fights for integrity and independence at gloomy Thornfield Hall.",
    coverUrl: "https://covers.openlibrary.org/b/id/9021984-M.jpg",
    ia: "janeeyre00bronrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1847,
  },
  {
    id: "bk-074",
    source: "vellum",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    category: "Literature",
    gradeLevel: "11",
    subject: "Gothic Fiction",
    language: "en",
    description: "The turbulent and tragic passion between Heathcliff and Catherine Earnshaw on the Yorkshire moors.",
    coverUrl: "https://covers.openlibrary.org/b/id/9121984-M.jpg",
    ia: "wutheringheights00bronrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1847,
  },
  {
    id: "bk-075",
    source: "vellum",
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    category: "Literature",
    gradeLevel: "6",
    subject: "Adventure",
    language: "en",
    description: "Jim Hawkins, Long John Silver, buried treasure, and mutiny aboard the Hispaniola.",
    coverUrl: "https://covers.openlibrary.org/b/id/9221984-M.jpg",
    ia: "treasureisland00stevrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1883,
  },
  {
    id: "bk-076",
    source: "vellum",
    title: "The Strange Case of Dr. Jekyll and Mr. Hyde",
    author: "Robert Louis Stevenson",
    category: "Literature",
    gradeLevel: "9",
    subject: "Gothic Fiction",
    language: "en",
    description: "A London physician uncovers the dual nature of man through a chemical potion.",
    coverUrl: "https://covers.openlibrary.org/b/id/9321984-M.jpg",
    ia: "strangecaseofdrj00stevrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1886,
  },
  {
    id: "bk-077",
    source: "vellum",
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    category: "Literature",
    gradeLevel: "6",
    subject: "Adventure",
    language: "en",
    description: "Boyhood adventures along the Mississippi River with Tom, Huck Finn, and Becky Thatcher.",
    coverUrl: "https://covers.openlibrary.org/b/id/9421984-M.jpg",
    ia: "adventurestomsaw00twairich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1876,
  },
  {
    id: "bk-078",
    source: "vellum",
    title: "Adventures of Huckleberry Finn",
    author: "Mark Twain",
    category: "Literature",
    gradeLevel: "10",
    subject: "Classics",
    language: "en",
    description: "Huck and the runaway slave Jim raft down the Mississippi, confronting morality and prejudice.",
    coverUrl: "https://covers.openlibrary.org/b/id/9521984-M.jpg",
    ia: "adventuresofhuck00twairich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1884,
  },
  {
    id: "bk-079",
    source: "vellum",
    title: "The Call of the Wild",
    author: "Jack London",
    category: "Literature",
    gradeLevel: "7",
    subject: "Adventure",
    language: "en",
    description: "Buck, a pampered family dog, is stolen and forced into the brutal life of a Yukon sled dog.",
    coverUrl: "https://covers.openlibrary.org/b/id/9621984-M.jpg",
    ia: "callofwild00londrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1903,
  },
  {
    id: "bk-080",
    source: "vellum",
    title: "White Fang",
    author: "Jack London",
    category: "Literature",
    gradeLevel: "7",
    subject: "Adventure",
    language: "en",
    description: "The reverse journey of a wild wolf-dog in the frozen Northwest finding trust with a patient human.",
    coverUrl: "https://covers.openlibrary.org/b/id/9721984-M.jpg",
    ia: "whitefang00londrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1906,
  },

  // --- PHILOSOPHY, CIVICS & SOCIAL SCIENCES (81-95) ---
  {
    id: "bk-081",
    source: "vellum",
    title: "The Republic of Plato",
    author: "Plato (tr. Benjamin Jowett)",
    category: "Philosophy",
    gradeLevel: "11",
    subject: "Political Philosophy",
    language: "en",
    description: "Socrates examines justice, the ideal city-state, the philosopher-king, and the Allegory of the Cave.",
    coverUrl: "https://covers.openlibrary.org/b/id/8031984-M.jpg",
    ia: "republicofplato01plat",
    isFeatured: true,
    isReadable: true,
    publishYear: 1888,
  },
  {
    id: "bk-082",
    source: "vellum",
    title: "The Nicomachean Ethics",
    author: "Aristotle (tr. F. H. Peters)",
    category: "Philosophy",
    gradeLevel: "12",
    subject: "Ethics",
    language: "en",
    description: "Inquiry into the highest human good (eudaimonia), moral virtue as the golden mean, and friendship.",
    coverUrl: "https://covers.openlibrary.org/b/id/8131984-M.jpg",
    ia: "nicomacheanethi00arisrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1881,
  },
  {
    id: "bk-083",
    source: "vellum",
    title: "Meditations",
    author: "Marcus Aurelius (tr. George Long)",
    category: "Philosophy",
    gradeLevel: "10",
    subject: "Stoicism",
    language: "en",
    description: "Personal spiritual reflections on Stoic virtue, inner resilience, duty, and accepting mortality.",
    coverUrl: "https://covers.openlibrary.org/b/id/8231984-M.jpg",
    ia: "thoughtsofemper00marc",
    isFeatured: true,
    isReadable: true,
    publishYear: 1862,
  },
  {
    id: "bk-084",
    source: "vellum",
    title: "The Prince",
    author: "Niccolò Machiavelli (tr. W. K. Marriott)",
    category: "Philosophy",
    gradeLevel: "11",
    subject: "Political Science",
    language: "en",
    description: "Treatise on statecraft, political pragmatism, warfare, and the maintenance of sovereign authority.",
    coverUrl: "https://covers.openlibrary.org/b/id/8331984-M.jpg",
    ia: "prince00machrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1532,
  },
  {
    id: "bk-085",
    source: "vellum",
    title: "Leviathan",
    author: "Thomas Hobbes",
    category: "Philosophy",
    gradeLevel: "12",
    subject: "Political Philosophy",
    language: "en",
    description: "The social contract theory, the state of nature, and the creation of an absolute commonwealth.",
    coverUrl: "https://covers.openlibrary.org/b/id/8431984-M.jpg",
    ia: "leviathanormatte00hobb",
    isFeatured: false,
    isReadable: true,
    publishYear: 1651,
  },
  {
    id: "bk-086",
    source: "vellum",
    title: "Two Treatises of Government",
    author: "John Locke",
    category: "Philosophy",
    gradeLevel: "11",
    subject: "Civics",
    language: "en",
    description: "Natural rights to life, liberty, and property, serving as the blueprint for democratic governance.",
    coverUrl: "https://covers.openlibrary.org/b/id/8531984-M.jpg",
    ia: "twotreatisesofgo00lockrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1689,
  },
  {
    id: "bk-087",
    source: "vellum",
    title: "The Social Contract",
    author: "Jean-Jacques Rousseau",
    category: "Philosophy",
    gradeLevel: "11",
    subject: "Political Science",
    language: "en",
    description: "'Man is born free, and everywhere he is in chains.' Foundations of the general will and popular sovereignty.",
    coverUrl: "https://covers.openlibrary.org/b/id/8631984-M.jpg",
    ia: "socialcontracto00rousrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1762,
  },
  {
    id: "bk-088",
    source: "vellum",
    title: "The Wealth of Nations",
    author: "Adam Smith",
    category: "Social Studies",
    gradeLevel: "12",
    subject: "Economics",
    language: "en",
    description: "The division of labor, productivity, market pricing, trade specialization, and the invisible hand.",
    coverUrl: "https://covers.openlibrary.org/b/id/8731984-M.jpg",
    ia: "inquiryintonatu01smitrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1776,
  },
  {
    id: "bk-089",
    source: "vellum",
    title: "On Liberty",
    author: "John Stuart Mill",
    category: "Philosophy",
    gradeLevel: "11",
    subject: "Political Philosophy",
    language: "en",
    description: "Defense of individual freedom of speech, expression, and the harm principle against tyranny.",
    coverUrl: "https://covers.openlibrary.org/b/id/8831984-M.jpg",
    ia: "onliberty00millrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1859,
  },
  {
    id: "bk-090",
    source: "vellum",
    title: "Self-Reliance and Other Essays",
    author: "Ralph Waldo Emerson",
    category: "Philosophy",
    gradeLevel: "10",
    subject: "Transcendentalism",
    language: "en",
    description: "Celebration of nonconformity, intellectual independence, original thinking, and inner conviction.",
    coverUrl: "https://covers.openlibrary.org/b/id/8931984-M.jpg",
    ia: "essays00emeruoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1841,
  },
  {
    id: "bk-091",
    source: "vellum",
    title: "Walden: Or, Life in the Woods",
    author: "Henry David Thoreau",
    category: "Social Studies",
    gradeLevel: "10",
    subject: "Environmental Ethics",
    language: "en",
    description: "Living deliberately in a simple cabin by Walden Pond, practicing self-sufficiency and mindful solitude.",
    coverUrl: "https://covers.openlibrary.org/b/id/9031984-M.jpg",
    ia: "waldenorlifeinwo00thorrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1854,
  },
  {
    id: "bk-092",
    source: "vellum",
    title: "Community Civics and Rural Life",
    author: "Arthur W. Dunn",
    category: "Textbook",
    gradeLevel: "8",
    subject: "Civics",
    language: "en",
    description: "Public health, civic responsibility, local governance, roads, taxation, and community cooperation.",
    coverUrl: "https://covers.openlibrary.org/b/id/7131984-M.jpg",
    ia: "communitycivics00dunnrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1920,
  },
  {
    id: "bk-093",
    source: "vellum",
    title: "Psychology: Briefer Course",
    author: "William James",
    category: "Social Studies",
    gradeLevel: "12",
    subject: "Psychology",
    language: "en",
    description: "Foundational psychology: stream of consciousness, sensory perception, memory, habits, and emotion.",
    coverUrl: "https://covers.openlibrary.org/b/id/7231984-M.jpg",
    ia: "psychologybriefer00jamerich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1892,
  },
  {
    id: "bk-094",
    source: "vellum",
    title: "The Interpretation of Dreams",
    author: "Sigmund Freud (tr. A. A. Brill)",
    category: "Social Studies",
    gradeLevel: "college",
    subject: "Psychology",
    language: "en",
    description: "Psychoanalytic theory introducing the unconscious mind, dream symbolism, and wish fulfillment.",
    coverUrl: "https://covers.openlibrary.org/b/id/7331984-M.jpg",
    ia: "interpretationof00freurich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1913,
  },
  {
    id: "bk-095",
    source: "vellum",
    title: "The School and Society",
    author: "John Dewey",
    category: "Social Studies",
    gradeLevel: "lifelong",
    subject: "Education",
    language: "en",
    description: "Progressive educational theory emphasizing hands-on learning, critical thinking, and student curiosity.",
    coverUrl: "https://covers.openlibrary.org/b/id/7431984-M.jpg",
    ia: "schoolsociety00deweuoft",
    isFeatured: false,
    isReadable: true,
    publishYear: 1899,
  },

  // --- TECHNOLOGY, INVENTIONS & APPLIED SCIENCES (96-105) ---
  {
    id: "bk-096",
    source: "vellum",
    title: "Inventors and Inventions",
    author: "F. L. Darrow",
    category: "Technology",
    gradeLevel: "7",
    subject: "Inventions",
    language: "en",
    description: "Stories of the steam engine, telegraph, printing press, phonograph, telephone, and automobile.",
    coverUrl: "https://covers.openlibrary.org/b/id/7531984-M.jpg",
    ia: "boysoflibraryin00darrrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1918,
  },
  {
    id: "bk-097",
    source: "vellum",
    title: "The Boy's Book of Inventions",
    author: "Ray Stannard Baker",
    category: "Technology",
    gradeLevel: "6",
    subject: "Engineering",
    language: "en",
    description: "Early accounts of submersibles, wireless telegraphy, motor carriages, and liquid air.",
    coverUrl: "https://covers.openlibrary.org/b/id/7631984-M.jpg",
    ia: "boysbookofinvent00bakerich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1899,
  },
  {
    id: "bk-098",
    source: "vellum",
    title: "Wireless Telegraphy and Telephony",
    author: "A. P. Morgan",
    category: "Technology",
    gradeLevel: "9",
    subject: "Electronics",
    language: "en",
    description: "Radio waves, antennas, spark transmitters, crystal detectors, and electromagnetic signaling.",
    coverUrl: "https://covers.openlibrary.org/b/id/7731984-M.jpg",
    ia: "wirelesstelegrap00morgrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1912,
  },
  {
    id: "bk-099",
    source: "vellum",
    title: "The Steam Engine: A Treatise on Steam Engines",
    author: "Arthur M. Wellington",
    category: "Technology",
    gradeLevel: "11",
    subject: "Mechanical Engineering",
    language: "en",
    description: "Boilers, pistons, indicator diagrams, thermal efficiency, and locomotives.",
    coverUrl: "https://covers.openlibrary.org/b/id/7831984-M.jpg",
    ia: "treatiseonsteame00wellrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1890,
  },
  {
    id: "bk-100",
    source: "vellum",
    title: "Aviation and Flying Machine Principles",
    author: "Victor W. Pagé",
    category: "Technology",
    gradeLevel: "10",
    subject: "Aeronautics",
    language: "en",
    description: "Aerodynamic lift, airfoils, fuselage construction, propeller thrust, and flight mechanics.",
    coverUrl: "https://covers.openlibrary.org/b/id/7931984-M.jpg",
    ia: "modernaircraftba00pagerich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1918,
  },
  {
    id: "bk-101",
    source: "vellum",
    title: "Elements of Machine Design",
    author: "W. Cawthorne Unwin",
    category: "Technology",
    gradeLevel: "college",
    subject: "Mechanical Engineering",
    language: "en",
    description: "Fastenings, shafts, gears, belts, lubrication, and structural stresses in industrial machinery.",
    coverUrl: "https://covers.openlibrary.org/b/id/8041984-M.jpg",
    ia: "elementsofmachi01unwirich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1901,
  },
  {
    id: "bk-102",
    source: "vellum",
    title: "The Automobile Handbook",
    author: "L. Elliott Brookes",
    category: "Technology",
    gradeLevel: "10",
    subject: "Automotive",
    language: "en",
    description: "Internal combustion engines, carburetors, ignition sparks, transmissions, and steering gear.",
    coverUrl: "https://covers.openlibrary.org/b/id/8141984-M.jpg",
    ia: "automobilehandbo00broorich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1910,
  },
  {
    id: "bk-103",
    source: "vellum",
    title: "Microscope and Its Revelations",
    author: "William B. Carpenter",
    category: "Technology",
    gradeLevel: "10",
    subject: "Optics",
    language: "en",
    description: "Design of optical lenses, slide staining, specimen preparation, and optical illumination.",
    coverUrl: "https://covers.openlibrary.org/b/id/8241984-M.jpg",
    ia: "microscopeitsrev00carprich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1901,
  },
  {
    id: "bk-104",
    source: "vellum",
    title: "The Practical Telephone Handbook",
    author: "Joseph Poole",
    category: "Technology",
    gradeLevel: "11",
    subject: "Telecommunications",
    language: "en",
    description: "Transmitters, switchboards, battery relays, transmission lines, and audio amplification.",
    coverUrl: "https://covers.openlibrary.org/b/id/8341984-M.jpg",
    ia: "practicaltelepho00poolrich",
    isFeatured: false,
    isReadable: true,
    publishYear: 1912,
  },
  {
    id: "bk-105",
    source: "vellum",
    title: "The Wonder Book of Knowledge",
    author: "Henry Chase Hill",
    category: "Technology",
    gradeLevel: "7",
    subject: "General Science",
    language: "en",
    description: "How paper is made, how glass is blown, how electricity travels through cables, and how submarines dive.",
    coverUrl: "https://covers.openlibrary.org/b/id/8441984-M.jpg",
    ia: "wonderbookofknow00hillrich",
    isFeatured: true,
    isReadable: true,
    publishYear: 1917,
  },
];
