export interface GameItem {
  id: string;
  title: string;
  subtitle: string;
  embedUrl: string;
  thumbnailUrl: string;
  genre: string;
  tags: string[];
}

export const ADDICTING_GAMES_CATALOG: GameItem[] = [
  {
    id: "ag-drift",
    title: "Addicting Drift",
    subtitle: "High speed drift racing with smooth physics, hairpin turns, and vehicle tuning.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/addicting-drift/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/addictingdrift.jpg",
    genre: "Racing",
    tags: ["Racing", "Cars", "Drifting", "Speed"],
  },
  {
    id: "ag-balloon-shoot",
    title: "Balloon Shoot",
    subtitle: "Fast-paced target shooting challenge. Aim sharp and clear the swirling vortex of balloons.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/balloon-shot/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/balloonshoot.jpg",
    genre: "Action",
    tags: ["Shooting", "Arcade", "Precision", "Reflex"],
  },
  {
    id: "ag-flags-maniac",
    title: "Flags Maniac",
    subtitle: "Test your global geography knowledge and recognize flags of every country under the clock.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/flags-maniac/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/Flags-Maniac.jpg",
    genre: "Puzzle",
    tags: ["Trivia", "Geography", "Flags", "Education"],
  },
  {
    id: "ag-glass-adventures",
    title: "Glass Adventures",
    subtitle: "Physics and gravity puzzle adventure. Direct the chemical flow through glass beakers.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/glass-adventures/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/glassadventures.jpg",
    genre: "Puzzle",
    tags: ["Physics", "Puzzle", "Logic", "Strategy"],
  },
  {
    id: "ag-eggcellent-equations",
    title: "Eggcellent Equations",
    subtitle: "Catch falling eggs by solving arithmetic equations quickly before they hit the ground.",
    embedUrl: "https://cdn.mathgames.com/content/eggcellent-equations/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/eggcellent-equations.jpg",
    genre: "Educational",
    tags: ["Math", "Equations", "Reflex", "Numbers"],
  },
  {
    id: "ag-flat-jewels",
    title: "Flat Jewels",
    subtitle: "Deep match-three strategy puzzle. Create chain reactions and earn high scoring combos.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/flat-jewels-match-3/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/flatjewelsgame.jpg",
    genre: "Puzzle",
    tags: ["Match 3", "Jewels", "Casual", "Strategy"],
  },
  {
    id: "ag-swatch-swap",
    title: "Swatch Swap",
    subtitle: "Color palette sorting puzzle. Swap color tiles in order to recreate harmonious gradients.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/swatch-swap/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/swatchswap.jpg",
    genre: "Puzzle",
    tags: ["Colors", "Brain", "Relax", "Logic"],
  },
  {
    id: "ag-tower-defense",
    title: "The Tower Defense",
    subtitle: "Tactical fortress defense. Place turrets, upgrade cannons, and stop advancing enemy waves.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/tower-defense-inlogic/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/image_2025-09-03_105109822.png",
    genre: "Strategy",
    tags: ["Tower Defense", "Strategy", "Tactics", "Action"],
  },
  {
    id: "ag-stunt-racing",
    title: "Addicting Stunt Racing",
    subtitle: "Strap in for extreme loop-de-loops, jumps, nitro speed boosts, and stunt courses.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/addicting-stunt-racing/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/addictingstuntracing.jpg",
    genre: "Racing",
    tags: ["Stunts", "Cars", "Nitro", "Racing"],
  },
  {
    id: "ag-hidden-math-gems",
    title: "Hidden Math Gems",
    subtitle: "Explore interactive math puzzles and unlock hidden gems with mental calculation.",
    embedUrl: "https://cdn.mathgames.com/content/hidden-math-gems/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/hidden%20math%20gemz.jpg",
    genre: "Educational",
    tags: ["Math", "Discovery", "Puzzles", "Logic"],
  },
  {
    id: "ag-bloxdhop",
    title: "Bloxdhop Parkour",
    subtitle: "First-person voxel jumping parkour. Jump across platforms, dodge pitfalls, and race friends.",
    embedUrl: "https://bloxdhop.io/",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/blosdhopio.jpg",
    genre: "Action",
    tags: ["Parkour", "Platformer", "Multiplayer", "Runner"],
  },
  {
    id: "ag-neon-block",
    title: "Neon Block",
    subtitle: "Fast arcade puzzle. Clear descending neon blocks by matching color sequences.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/neon-block/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/neonblock.jpg",
    genre: "Arcade",
    tags: ["Neon", "Blocks", "Arcade", "Fast"],
  },
  {
    id: "ag-math-madness",
    title: "Math Madness",
    subtitle: "Rapid arithmetic blitz. Train your mental agility against the ticking timer.",
    embedUrl: "https://cdn.mathgames.com/content/math-madness/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/mathmadness.jpg",
    genre: "Educational",
    tags: ["Math", "Speed", "Brain Training", "Quiz"],
  },
  {
    id: "ag-heatwave-antarctica",
    title: "Heatwave Antarctica",
    subtitle: "Environmental strategy puzzle. Balance climate temperature nodes across the icy tundra.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/heatwave-antarctica/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/heatwaveantartica.jpg",
    genre: "Strategy",
    tags: ["Puzzle", "Strategy", "Climate", "Science"],
  },
  {
    id: "ag-fill-the-holes",
    title: "Fill The Holes",
    subtitle: "Three shapes, three colors, infinite challenge. Rapid geometric pattern matching.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/fill-the-holes/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/filltheholes.jpg",
    genre: "Arcade",
    tags: ["Geometry", "Shapes", "Reflex", "Patterns"],
  },
  {
    id: "ag-pull-the-thread",
    title: "Pull The Thread",
    subtitle: "Tangling knot unraveling puzzle. Pull lines and threads to untie complex geometric knots.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/pull-the-thread/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/pullthethread.jpg",
    genre: "Puzzle",
    tags: ["Knots", "Brain", "Relax", "Logic"],
  },
  {
    id: "ag-fishington",
    title: "Fishington",
    subtitle: "Relaxing multiplayer fishing getaway. Cast your line, catch rare fish, and upgrade tackle.",
    embedUrl: "https://fishington.io/",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/fishington.jpg",
    genre: "Casual",
    tags: ["Fishing", "Relax", "Multiplayer", "Casual"],
  },
  {
    id: "ag-number-frenzy",
    title: "Number Frenzy",
    subtitle: "Find matching sum sequences on a grid. Fun math puzzle that sharpens observation.",
    embedUrl: "https://cdn.mathgames.com/content/number-frenzy/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/numberfrenzy.jpg",
    genre: "Educational",
    tags: ["Numbers", "Math", "Grid", "Puzzles"],
  },
  {
    id: "ag-black-thrones",
    title: "Black Thrones",
    subtitle: "Dark fantasy side-scrolling endless runner. Dodge traps, jump chasms, and slice enemies.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/black-thrones/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/blackthorns.jpg",
    genre: "Action",
    tags: ["Runner", "Fantasy", "Action", "Sword"],
  },
  {
    id: "ag-switch-hexagon",
    title: "Switch Hexagon",
    subtitle: "Hyper-speed geometric runner. Rotate and switch hexagon lanes to pass barriers.",
    embedUrl: "https://cdn2.addictinggames.com/addictinggames-content/ag-assets/content-items/html5-games/switch-hexagon/index.html",
    thumbnailUrl: "https://prod.addictinggames.com/sites/default/files/switchhexagon.jpg",
    genre: "Arcade",
    tags: ["Hexagon", "Reflex", "Speed", "Geometric"],
  },
];
